-- Optional manual table script for Neon PostgreSQL.
-- The API also calls EnsureCreated() on startup, so this script is normally not required.

CREATE TABLE IF NOT EXISTS "ContactMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL,
    "Email" varchar(255) NOT NULL,
    "Subject" varchar(180) NOT NULL,
    "InquiryType" varchar(80) NOT NULL,
    "Message" varchar(2000) NOT NULL,
    "IpAddress" varchar(64),
    "UserAgent" varchar(512),
    "SubmittedAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "IsRead" boolean NOT NULL DEFAULT false,
    "EmailNotificationSent" boolean NOT NULL DEFAULT false,
    "EmailFailureReason" text
);

CREATE INDEX IF NOT EXISTS "IX_ContactMessages_SubmittedAtUtc" ON "ContactMessages" ("SubmittedAtUtc");
CREATE INDEX IF NOT EXISTS "IX_ContactMessages_Email" ON "ContactMessages" ("Email");
